### ISSUE TITLE
any help with this error?

### ISSUE THREAD

**Issue by lostroes** [deepakkumar132/Discord-Token-Generator#4]
14:48:33 | GENERATOR | i > Starting generator...
Exception in thread Thread-1 (runThread):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-3 (runThread):
Exception in thread Thread-2 (runThread):
Traceback (most recent call last):
Exception in thread Thread-5 (runThread):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 173, in runThread
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 173, in runThread
    creator(threadNum, invite).start()
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 64, in __init__
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 173, in runThread
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 173, in runThread
    creator(threadNum, invite).start()
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 64, in __init__
    super().__init__(taskId)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\src\base.py", line 16, in __init__
    creator(threadNum, invite).start()
    creator(threadNum, invite).start()
    super().__init__(taskId)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\src\base.py", line 16, in __init__
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 64, in __init__
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 64, in __init__
    self.proxy = f"http://{random.choice(proxies)}"
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    self.proxy = f"http://{random.choice(proxies)}"
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    super().__init__(taskId)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\src\base.py", line 16, in __init__
    return seq[self._randbelow(len(seq))]
Exception in thread Thread-4 (runThread):
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
    self.proxy = f"http://{random.choice(proxies)}"
IndexError: list index out of range
    super().__init__(taskId)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\src\base.py", line 16, in __init__
Traceback (most recent call last):
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
    self.proxy = f"http://{random.choice(proxies)}"
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 173, in runThread
    creator(threadNum, invite).start()
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\main.py", line 64, in __init__
    super().__init__(taskId)
  File "C:\Users\user\OneDrive\Desktop\Discord-Token-Generator-main\src\base.py", line 16, in __init__
    self.proxy = f"http://{random.choice(proxies)}"
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by deepakkumar132** [comment]
Check proxies format

**Comment by lostroes** [comment]
i did now its just stuck on starting generator...
![image](https://user-images.githubusercontent.com/80589822/233655109-8c9efe35-c657-4842-a9d3-0a4aed738b76.png)

**Comment by deepakkumar132** [comment]
which captcha api are you using ?

**Comment by lostroes** [comment]
CAPMONSTER
